# Generated by Django 6.0.2 on 2026-02-05 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nom du Département')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code (ex: INFO, GC)')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL, verbose_name='Chef de Département')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la Filière')),
                ('code', models.CharField(max_length=10, verbose_name='Code (ex: GI, RT)')),
                ('niveau', models.CharField(choices=[('LICENSE', 'Licence'), ('MASTER', 'Master'), ('DOCTORAT', 'Doctorat')], default='LICENSE', max_length=50)),
                ('capacity', models.PositiveIntegerField(default=30, verbose_name="Capacité d'accueil")),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='core.departement', verbose_name='Département')),
            ],
            options={
                'verbose_name': 'Filière',
                'verbose_name_plural': 'Filières',
                'ordering': ['departement', 'name'],
                'unique_together': {('code', 'departement')},
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='Format: 2024-2025', max_length=9, verbose_name='Année Universitaire')),
                ('status', models.CharField(choices=[('PENDING', 'En Attente'), ('VALIDATED', 'Validée'), ('REJECTED', 'Rejetée')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('validation_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Motif de rejet')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de demande')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='core.filiere', verbose_name='Filière')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'ETUDIANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
                ('validated_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'filiere', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du Module')),
                ('code', models.CharField(max_length=20, verbose_name='Code Module')),
                ('semestre', models.IntegerField(choices=[(1, 'S1'), (2, 'S2'), (3, 'S3'), (4, 'S4'), (5, 'S5'), (6, 'S6')], default=1, verbose_name='Semestre')),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('heures_cm', models.PositiveIntegerField(default=0, verbose_name='Heures CM')),
                ('heures_td', models.PositiveIntegerField(default=0, verbose_name='Heures TD')),
                ('heures_tp', models.PositiveIntegerField(default=0, verbose_name='Heures TP')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enseignant', models.ForeignKey(blank=True, limit_choices_to={'role': 'ENSEIGNANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules_enseignes', to=settings.AUTH_USER_MODEL, verbose_name='Enseignant Responsable')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.filiere', verbose_name='Filière')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['filiere', 'semestre', 'name'],
                'unique_together': {('code', 'filiere')},
            },
        ),
    ]
