# Generated by Django 6.0.2 on 2026-02-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='certificat_scolarite',
            field=models.FileField(blank=True, upload_to='inscriptions/certificats/'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='photo_identite',
            field=models.ImageField(blank=True, upload_to='inscriptions/photos/'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='releve_notes',
            field=models.FileField(blank=True, upload_to='inscriptions/releves/'),
        ),
    ]
