# Generated by Django 6.0.2 on 2026-02-05 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_inscription_certificat_scolarite_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='Format: 2024-2025', max_length=9, verbose_name='Année Universitaire')),
                ('note_controle', models.DecimalField(blank=True, decimal_places=2, help_text='Note sur 20', max_digits=5, null=True, verbose_name='Note Contrôle')),
                ('note_examen', models.DecimalField(blank=True, decimal_places=2, help_text='Note sur 20', max_digits=5, null=True, verbose_name='Note Examen')),
                ('note_finale', models.DecimalField(blank=True, decimal_places=2, help_text='Moyenne calculée', max_digits=5, null=True, verbose_name='Note Finale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.module', verbose_name='Module')),
                ('saisie_par', models.ForeignKey(blank=True, limit_choices_to={'role': 'ENSEIGNANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_saisies', to=settings.AUTH_USER_MODEL, verbose_name='Saisi par')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'ETUDIANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-academic_year', 'module', 'student'],
                'unique_together': {('student', 'module', 'academic_year')},
            },
        ),
    ]
